[project]
name = "plexos-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Felipe Bastidas", email = "felipe.bastidas@coordinador.cl" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
]

[project.scripts]
plexos-db = "plexos_db.cli.main:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
